# Generated by Django 5.2.4 on 2025-07-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookshelf', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
