# Generated by Django 5.2.4 on 2025-07-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookshelf', '0007_tag_book_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
