# Generated by Django 5.2.4 on 2025-07-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookshelf', '0008_tag_slug_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='books', to='Bookshelf.tag'),
        ),
    ]
